### ISSUE TITLE
dApp for inserting new types

### ISSUE THREAD

**Issue by ctzurcanu** [ctzurcanu/dType#3]
Should:
1. make a cache of all dType data into a .json file
2. present the available types for the insert/update form
3. ability to re-order, delete, add to types array
4. operate the insert/update

5. extra: process a batch of inserts (from a .json)

**Comment by loredanacirstea** [comment]
- external link button for contract address to etherscan
- external link button for contract source to swarm gateway

- types should be human readable - browsing + selection

**Comment by loredanacirstea** [comment]
Done. Opened issues for what is not done.
